# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='linkto',
        ),
    ]
