# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_project_linkto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkto',
            field=models.URLField(default='SOME STRING'),
        ),
    ]
